// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBVkDFEjEd-rKvb_fpezjFSS0mLWcRQyok',
    appId: '1:557322767442:web:a9c79703be2ef80d55a38b',
    messagingSenderId: '557322767442',
    projectId: 'ecom-2c53d',
    authDomain: 'ecom-2c53d.firebaseapp.com',
    storageBucket: 'ecom-2c53d.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDwJ3TpAMpmSuSQq4Fvf46YwpiA3jvUnzs',
    appId: '1:557322767442:android:a9626185275c1dee55a38b',
    messagingSenderId: '557322767442',
    projectId: 'ecom-2c53d',
    storageBucket: 'ecom-2c53d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCKqYe1OkVP_iMHnZPrCVxEW1W7lCbUx2Q',
    appId: '1:557322767442:ios:bdfaed8e5d50035c55a38b',
    messagingSenderId: '557322767442',
    projectId: 'ecom-2c53d',
    storageBucket: 'ecom-2c53d.appspot.com',
    iosBundleId: 'com.example.flutterApplication2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCKqYe1OkVP_iMHnZPrCVxEW1W7lCbUx2Q',
    appId: '1:557322767442:ios:692cc3c65fec5ee055a38b',
    messagingSenderId: '557322767442',
    projectId: 'ecom-2c53d',
    storageBucket: 'ecom-2c53d.appspot.com',
    iosBundleId: 'com.example.flutterApplication2.RunnerTests',
  );
}
